import path from 'node:path'
import process from 'node:process'
import { parseJson } from '@dcloudio/uni-cli-shared'
import vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vitest/config'

/**
 * 生成后的 src/pages.json 带 `// GENERATED BY UNI-PAGES` 注释，是 JSONC 而不是严格 JSON，
 * vite 内置的 json 插件解析不了（`pnpm dev`/`build` 跑过之后，任何 import 到
 * `@/pages.json` 的测试都会报 "Failed to parse JSON file"）。
 * 这里用项目构建时同一个解析器把注释去掉，保证测试和构建对 pages.json 的理解一致。
 */
function stripPagesJsonComments() {
  return {
    name: 'test-strip-pages-json-comments',
    enforce: 'pre' as const,
    transform(code: string, id: string) {
      if (!id.endsWith('pages.json')) {
        return
      }
      return { code: JSON.stringify(parseJson(code, true, 'pages.json')), map: null }
    },
  }
}

export default defineConfig({
  plugins: [stripPagesJsonComments(), vue()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['src/test-setup.ts'],
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['node_modules', 'src/uni_modules/**'],
  },
  resolve: {
    alias: {
      '@': path.resolve(process.cwd(), 'src'),
      '@img': path.resolve(process.cwd(), 'src/static/images'),
    },
  },
})
