###################################
server.port=11000
##################mysql##################
resume.mysql.ip=127.0.0.1
resume.mysql.port=3306
resume.mysql.db=resume
resume.mysql.username=root
resume.mysql.password=123456
##################redis##################
resume.redis.host=127.0.0.1
resume.redis.port=6379
resume.redis.index=2
resume.redis.password=123456
##################wechat##################
resume.wechat.appid=
resume.wechat.appSecret=
resume.wechat.redirectUri=
##################url##################
resume.url.front=http://localhost:11000
resume.url.backend=http://localhost:17000
##################oss##################
resume.oss.type=1
resume.oss.minio.endpoint=http://127.0.0.1:9000/
resume.oss.minio.bucketName=resume
resume.oss.minio.accessKey=minioadmin
resume.oss.minio.secretKey=minioadmin
resume.oss.aliyun.endpoint=
resume.oss.aliyun.accessKey=
resume.oss.aliyun.secretKey=
resume.oss.aliyun.bucketName=
resume.oss.local.path=D:/project/oss/resume/
##################email##################
resume.mail.host=smtp.qq.com
resume.mail.port=587
resume.mail.username=2770063826@qq.com
resume.mail.password=gwrmkvvsnkztdehj
##################export##################
resume.system.export.preview-url=http://127.0.0.1:9001/#/pages/export/index
resume.system.export.timeout=60000