import type { IComposition, IResumeTemplate } from './types'

/**
 * 由 resume-design 的模板 JSON（doc/简历模板.json）转换而来，
 * 通过 scripts/convert-templates.mjs 生成，如需调整请改脚本后重新生成。
 */

export const DESIGN_COMPOSITIONS: Record<string, IComposition> = {
  /** 由 resume-design 模板转换而来 */
  'design-1': {
    layout: 'leftRight',
    modules: [
      { model: 'BASE_INFO', cptName: 'BASE_INFO_2', side: 'left' },
      { model: 'SKILL_SPECIALTIES', cptName: 'SKILL_SPECIALTIES_2', side: 'left' },
      { model: 'CUSTOM', cptName: 'CUSTOM_1', side: 'right' },
      { model: 'JOB_INTENTION', side: 'right' },
      { model: 'EDU_BACKGROUND', cptName: 'EDU_BACKGROUND_2', side: 'right' },
      { model: 'CAMPUS_EXPERIENCE', side: 'right' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'right' },
      { model: 'WORK_EXPERIENCE', cptName: 'WORK_EXPERIENCE_2', side: 'right' },
      { model: 'PROJECT_EXPERIENCE', side: 'right' },
      { model: 'AWARDS', side: 'right' },
      { model: 'HOBBIES', side: 'right' },
      { model: 'SELF_EVALUATION', side: 'right' },
      { model: 'WORKS_DISPLAY', side: 'right' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-2': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', cptName: 'BASE_INFO_3', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-3': {
    layout: 'classical',
    modules: [
      { model: 'RESUME_TITLE', cptName: 'RESUME_TITLE_1', side: 'main' },
      { model: 'BASE_INFO', cptName: 'BASE_INFO_1', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-4': {
    layout: 'leftRight',
    modules: [
      { model: 'BASE_INFO', cptName: 'BASE_INFO_2', side: 'left' },
      { model: 'SKILL_SPECIALTIES', cptName: 'SKILL_SPECIALTIES_2', side: 'left' },
      { model: 'CUSTOM', cptName: 'CUSTOM_1', side: 'right' },
      { model: 'JOB_INTENTION', side: 'right' },
      { model: 'EDU_BACKGROUND', cptName: 'EDU_BACKGROUND_2', side: 'right' },
      { model: 'CAMPUS_EXPERIENCE', side: 'right' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'right' },
      { model: 'WORK_EXPERIENCE', cptName: 'WORK_EXPERIENCE_2', side: 'right' },
      { model: 'PROJECT_EXPERIENCE', side: 'right' },
      { model: 'AWARDS', side: 'right' },
      { model: 'HOBBIES', side: 'right' },
      { model: 'SELF_EVALUATION', side: 'right' },
      { model: 'WORKS_DISPLAY', side: 'right' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-5': {
    layout: 'classical',
    modules: [
      { model: 'CUSTOM', side: 'main' },
      { model: 'BASE_INFO', cptName: 'BASE_INFO_4', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-6': {
    layout: 'classical',
    modules: [
      { model: 'RESUME_TITLE', cptName: 'RESUME_TITLE_1', side: 'main' },
      { model: 'BASE_INFO', cptName: 'BASE_INFO_1', side: 'main' },
      { model: 'JOB_INTENTION', cptName: 'JOB_INTENTION_1', side: 'main' },
      { model: 'EDU_BACKGROUND', cptName: 'EDU_BACKGROUND_1', side: 'main' },
      { model: 'SKILL_SPECIALTIES', cptName: 'SKILL_SPECIALTIES_1', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', cptName: 'CAMPUS_EXPERIENCE_1', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', cptName: 'INTERNSHIP_EXPERIENCE_1', side: 'main' },
      { model: 'WORK_EXPERIENCE', cptName: 'WORK_EXPERIENCE_1', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', cptName: 'PROJECT_EXPERIENCE_1', side: 'main' },
      { model: 'AWARDS', cptName: 'AWARDS_1', side: 'main' },
      { model: 'HOBBIES', cptName: 'HOBBIES_1', side: 'main' },
      { model: 'SELF_EVALUATION', cptName: 'SELF_EVALUATION_1', side: 'main' },
      { model: 'WORKS_DISPLAY', cptName: 'WORKS_DISPLAY_1', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-7': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-8': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-9': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-10': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-11': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', cptName: 'BASE_INFO_1', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-12': {
    layout: 'leftRight',
    modules: [
      { model: 'BASE_INFO', cptName: 'BASE_INFO_2', side: 'left' },
      { model: 'SKILL_SPECIALTIES', cptName: 'SKILL_SPECIALTIES_2', side: 'left' },
      { model: 'CUSTOM', side: 'right' },
      { model: 'JOB_INTENTION', side: 'right' },
      { model: 'EDU_BACKGROUND', side: 'right' },
      { model: 'CAMPUS_EXPERIENCE', side: 'right' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'right' },
      { model: 'WORK_EXPERIENCE', side: 'right' },
      { model: 'PROJECT_EXPERIENCE', side: 'right' },
      { model: 'AWARDS', side: 'right' },
      { model: 'HOBBIES', side: 'right' },
      { model: 'SELF_EVALUATION', side: 'right' },
      { model: 'WORKS_DISPLAY', side: 'right' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-13': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-14': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', cptName: 'BASE_INFO_1', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-15': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-16': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', cptName: 'BASE_INFO_1', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-17': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-18': {
    layout: 'leftRight',
    modules: [
      { model: 'BASE_INFO', cptName: 'BASE_INFO_2', side: 'left' },
      { model: 'SKILL_SPECIALTIES', cptName: 'SKILL_SPECIALTIES_2', side: 'left' },
      { model: 'CUSTOM', side: 'right' },
      { model: 'JOB_INTENTION', side: 'right' },
      { model: 'EDU_BACKGROUND', side: 'right' },
      { model: 'CAMPUS_EXPERIENCE', side: 'right' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'right' },
      { model: 'WORK_EXPERIENCE', side: 'right' },
      { model: 'PROJECT_EXPERIENCE', side: 'right' },
      { model: 'AWARDS', side: 'right' },
      { model: 'HOBBIES', side: 'right' },
      { model: 'WORKS_DISPLAY', side: 'right' },
      { model: 'SELF_EVALUATION', side: 'right' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-19': {
    layout: 'classical',
    modules: [
      { model: 'RESUME_TITLE', cptName: 'RESUME_TITLE_2', side: 'main' },
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-20': {
    layout: 'classical',
    modules: [
      { model: 'RESUME_TITLE', cptName: 'RESUME_TITLE_2', side: 'main' },
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-21': {
    layout: 'classical',
    modules: [
      { model: 'RESUME_TITLE', cptName: 'RESUME_TITLE_2', side: 'main' },
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-22': {
    layout: 'leftRight',
    modules: [
      { model: 'BASE_INFO', cptName: 'BASE_INFO_2', side: 'left' },
      { model: 'SKILL_SPECIALTIES', cptName: 'SKILL_SPECIALTIES_2', side: 'left' },
      { model: 'CUSTOM', cptName: 'CUSTOM_1', side: 'right' },
      { model: 'JOB_INTENTION', side: 'right' },
      { model: 'EDU_BACKGROUND', side: 'right' },
      { model: 'CAMPUS_EXPERIENCE', side: 'right' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'right' },
      { model: 'WORK_EXPERIENCE', side: 'right' },
      { model: 'PROJECT_EXPERIENCE', side: 'right' },
      { model: 'AWARDS', side: 'right' },
      { model: 'HOBBIES', side: 'right' },
      { model: 'SELF_EVALUATION', side: 'right' },
      { model: 'WORKS_DISPLAY', side: 'right' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-23': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-24': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },
  /** 由 resume-design 模板转换而来 */
  'design-25': {
    layout: 'classical',
    modules: [
      { model: 'BASE_INFO', side: 'main' },
      { model: 'JOB_INTENTION', side: 'main' },
      { model: 'SKILL_SPECIALTIES', side: 'main' },
      { model: 'EDU_BACKGROUND', side: 'main' },
      { model: 'CAMPUS_EXPERIENCE', side: 'main' },
      { model: 'INTERNSHIP_EXPERIENCE', side: 'main' },
      { model: 'WORK_EXPERIENCE', side: 'main' },
      { model: 'PROJECT_EXPERIENCE', side: 'main' },
      { model: 'AWARDS', side: 'main' },
      { model: 'HOBBIES', side: 'main' },
      { model: 'SELF_EVALUATION', side: 'main' },
      { model: 'WORKS_DISPLAY', side: 'main' },
    ],
  },

}

export const DESIGN_TEMPLATES: IResumeTemplate[] = [
  {
    id: 'design-1',
    name: '设计风格 1',
    description: '两栏布局，#254665 主题色',
    cover: '',
    composition: 'design-1',
    style: {
      themeColor: '#254665',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pTop: '0',
      pBottom: '30px',
      pLeftRight: '30px',
      mTop: '0px',
      mBottom: '0px',
      leftWidth: '270px',
      rightWidth: '550px',
      leftThemeColor: '#254665',
    },
  },
  {
    id: 'design-2',
    name: '设计风格 2',
    description: '单栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-2',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pTop: '0',
      pBottom: '30px',
      pLeftRight: '50px',
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-3',
    name: '设计风格 3',
    description: '单栏布局，#4d4d4d 主题色',
    cover: '',
    composition: 'design-3',
    style: {
      themeColor: '#4d4d4d',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-4',
    name: '设计风格 4',
    description: '两栏布局，#647ec9 主题色',
    cover: '',
    composition: 'design-4',
    style: {
      themeColor: '#647ec9',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      mTop: '0px',
      mBottom: '45px',
      leftWidth: '270px',
      rightWidth: '550px',
      leftThemeColor: '#967a5b',
      rightThemeColor: '#ffffff',
    },
  },
  {
    id: 'design-5',
    name: '设计风格 5',
    description: '单栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-5',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-6',
    name: '设计风格 6',
    description: '单栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-6',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pTop: '0',
      pBottom: '30px',
      pLeftRight: '40px',
      mTop: '0px',
      mBottom: '0px',
    },
  },
  {
    id: 'design-7',
    name: '设计风格 7',
    description: '单栏布局，#da180f 主题色',
    cover: '',
    composition: 'design-7',
    style: {
      themeColor: '#da180f',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-8',
    name: '设计风格 8',
    description: '单栏布局，#3390cd 主题色',
    cover: '',
    composition: 'design-8',
    style: {
      themeColor: '#3390cd',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-9',
    name: '设计风格 9',
    description: '单栏布局，#808080 主题色',
    cover: '',
    composition: 'design-9',
    style: {
      themeColor: '#808080',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-10',
    name: '设计风格 10',
    description: '单栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-10',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-11',
    name: '设计风格 11',
    description: '单栏布局，#3390cd 主题色',
    cover: '',
    composition: 'design-11',
    style: {
      themeColor: '#3390cd',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-12',
    name: '设计风格 12',
    description: '两栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-12',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '18px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pLeftRight: '19px',
      mTop: '0px',
      mBottom: '45px',
      leftWidth: '270px',
      rightWidth: '550px',
      leftThemeColor: '#324860',
      rightThemeColor: '#fff',
    },
  },
  {
    id: 'design-13',
    name: '设计风格 13',
    description: '单栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-13',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pTop: '10px',
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-14',
    name: '设计风格 14',
    description: '单栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-14',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pLeftRight: '40px',
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-15',
    name: '设计风格 15',
    description: '单栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-15',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-16',
    name: '设计风格 16',
    description: '单栏布局，#254665 主题色',
    cover: '',
    composition: 'design-16',
    style: {
      themeColor: '#254665',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pTop: '37px',
      pBottom: '10px',
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-17',
    name: '设计风格 17',
    description: '单栏布局，#dd415e 主题色',
    cover: '',
    composition: 'design-17',
    style: {
      themeColor: '#dd415e',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pTop: '37px',
      pBottom: '10px',
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-18',
    name: '设计风格 18',
    description: '两栏布局，#3390cd 主题色',
    cover: '',
    composition: 'design-18',
    style: {
      themeColor: '#3390cd',
      firstTitleFontSize: '16px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pTop: '0px',
      pLeftRight: '13px',
      mTop: '0px',
      mBottom: '9px',
      leftWidth: '270px',
      rightWidth: '550px',
      leftThemeColor: '#3390cd',
      rightThemeColor: '#fff',
    },
  },
  {
    id: 'design-19',
    name: '设计风格 19',
    description: '单栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-19',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pTop: '0px',
      pBottom: '30px',
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-20',
    name: '设计风格 20',
    description: '单栏布局，#967a5b 主题色',
    cover: '',
    composition: 'design-20',
    style: {
      themeColor: '#967a5b',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pTop: '0px',
      pBottom: '24px',
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-21',
    name: '设计风格 21',
    description: '单栏布局，#3390cd 主题色',
    cover: '',
    composition: 'design-21',
    style: {
      themeColor: '#3390cd',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pTop: '0px',
      pBottom: '30px',
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-22',
    name: '设计风格 22',
    description: '两栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-22',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '16px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pTop: '0px',
      pLeftRight: '15px',
      mTop: '0px',
      mBottom: '45px',
      leftWidth: '270px',
      rightWidth: '550px',
      leftThemeColor: '#81778e',
      rightThemeColor: '#fff',
    },
  },
  {
    id: 'design-23',
    name: '设计风格 23',
    description: '单栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-23',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      pLeftRight: '55px',
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-24',
    name: '设计风格 24',
    description: '单栏布局，#079cfa 主题色',
    cover: '',
    composition: 'design-24',
    style: {
      themeColor: '#079cfa',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#666',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#757575',
      textFontWeight: 500,
      mTop: '0px',
      mBottom: '45px',
    },
  },
  {
    id: 'design-25',
    name: '设计风格 25',
    description: '单栏布局，#eeece1 主题色',
    cover: '',
    composition: 'design-25',
    style: {
      themeColor: '#eeece1',
      firstTitleFontSize: '20px',
      titleFontSize: '14px',
      titleColor: '#808080',
      titleFontWeight: 600,
      textFontSize: '14px',
      textColor: '#242424',
      textFontWeight: 500,
      mTop: '0px',
      mBottom: '45px',
    },
  },

]
